// Interop oracle schema: every proto3 scalar type plus repeated,
// nested, and enum fields. Used by run.sh to cross-validate the V
// runtime against protoc byte-for-byte.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: scalars.proto

package scalars

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Color int32

const (
	Color_COLOR_UNSPECIFIED Color = 0
	Color_RED               Color = 1
	Color_GREEN             Color = 2
	Color_BLUE              Color = 3
)

// Enum value maps for Color.
var (
	Color_name = map[int32]string{
		0: "COLOR_UNSPECIFIED",
		1: "RED",
		2: "GREEN",
		3: "BLUE",
	}
	Color_value = map[string]int32{
		"COLOR_UNSPECIFIED": 0,
		"RED":               1,
		"GREEN":             2,
		"BLUE":              3,
	}
)

func (x Color) Enum() *Color {
	p := new(Color)
	*p = x
	return p
}

func (x Color) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Color) Descriptor() protoreflect.EnumDescriptor {
	return file_scalars_proto_enumTypes[0].Descriptor()
}

func (Color) Type() protoreflect.EnumType {
	return &file_scalars_proto_enumTypes[0]
}

func (x Color) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Color.Descriptor instead.
func (Color) EnumDescriptor() ([]byte, []int) {
	return file_scalars_proto_rawDescGZIP(), []int{0}
}

type Nested struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Num           int32                  `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Nested) Reset() {
	*x = Nested{}
	mi := &file_scalars_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nested) ProtoMessage() {}

func (x *Nested) ProtoReflect() protoreflect.Message {
	mi := &file_scalars_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nested.ProtoReflect.Descriptor instead.
func (*Nested) Descriptor() ([]byte, []int) {
	return file_scalars_proto_rawDescGZIP(), []int{0}
}

func (x *Nested) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Nested) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

type Scalars struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	A      int32                  `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B      int64                  `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	C      uint32                 `protobuf:"varint,3,opt,name=c,proto3" json:"c,omitempty"`
	D      uint64                 `protobuf:"varint,4,opt,name=d,proto3" json:"d,omitempty"`
	E      int32                  `protobuf:"zigzag32,5,opt,name=e,proto3" json:"e,omitempty"`
	F      int64                  `protobuf:"zigzag64,6,opt,name=f,proto3" json:"f,omitempty"`
	G      bool                   `protobuf:"varint,7,opt,name=g,proto3" json:"g,omitempty"`
	H      string                 `protobuf:"bytes,8,opt,name=h,proto3" json:"h,omitempty"`
	I      []byte                 `protobuf:"bytes,9,opt,name=i,proto3" json:"i,omitempty"`
	J      float32                `protobuf:"fixed32,10,opt,name=j,proto3" json:"j,omitempty"`
	K      float64                `protobuf:"fixed64,11,opt,name=k,proto3" json:"k,omitempty"`
	L      uint32                 `protobuf:"fixed32,12,opt,name=l,proto3" json:"l,omitempty"`
	M      uint64                 `protobuf:"fixed64,13,opt,name=m,proto3" json:"m,omitempty"`
	N      int32                  `protobuf:"fixed32,14,opt,name=n,proto3" json:"n,omitempty"`
	O      int64                  `protobuf:"fixed64,15,opt,name=o,proto3" json:"o,omitempty"`
	P      Color                  `protobuf:"varint,16,opt,name=p,proto3,enum=Color" json:"p,omitempty"`
	Rp     []int32                `protobuf:"varint,17,rep,packed,name=rp,proto3" json:"rp,omitempty"`
	Rs     []string               `protobuf:"bytes,18,rep,name=rs,proto3" json:"rs,omitempty"`
	Nested *Nested                `protobuf:"bytes,19,opt,name=nested,proto3" json:"nested,omitempty"`
	Rn     []*Nested              `protobuf:"bytes,20,rep,name=rn,proto3" json:"rn,omitempty"`
	Mi     map[int32]int32        `protobuf:"bytes,21,rep,name=mi,proto3" json:"mi,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Ms     map[string]string      `protobuf:"bytes,22,rep,name=ms,proto3" json:"ms,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Mn     map[string]*Nested     `protobuf:"bytes,23,rep,name=mn,proto3" json:"mn,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Mc     map[uint32]Color       `protobuf:"bytes,24,rep,name=mc,proto3" json:"mc,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=Color"`
	Mb     map[int64]bool         `protobuf:"bytes,25,rep,name=mb,proto3" json:"mb,omitempty" protobuf_key:"zigzag64,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Types that are valid to be assigned to Choice:
	//
	//	*Scalars_Ci
	//	*Scalars_Cs
	//	*Scalars_Cn
	Choice        isScalars_Choice       `protobuf_oneof:"choice"`
	Ts            *timestamppb.Timestamp `protobuf:"bytes,29,opt,name=ts,proto3" json:"ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scalars) Reset() {
	*x = Scalars{}
	mi := &file_scalars_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scalars) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scalars) ProtoMessage() {}

func (x *Scalars) ProtoReflect() protoreflect.Message {
	mi := &file_scalars_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scalars.ProtoReflect.Descriptor instead.
func (*Scalars) Descriptor() ([]byte, []int) {
	return file_scalars_proto_rawDescGZIP(), []int{1}
}

func (x *Scalars) GetA() int32 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *Scalars) GetB() int64 {
	if x != nil {
		return x.B
	}
	return 0
}

func (x *Scalars) GetC() uint32 {
	if x != nil {
		return x.C
	}
	return 0
}

func (x *Scalars) GetD() uint64 {
	if x != nil {
		return x.D
	}
	return 0
}

func (x *Scalars) GetE() int32 {
	if x != nil {
		return x.E
	}
	return 0
}

func (x *Scalars) GetF() int64 {
	if x != nil {
		return x.F
	}
	return 0
}

func (x *Scalars) GetG() bool {
	if x != nil {
		return x.G
	}
	return false
}

func (x *Scalars) GetH() string {
	if x != nil {
		return x.H
	}
	return ""
}

func (x *Scalars) GetI() []byte {
	if x != nil {
		return x.I
	}
	return nil
}

func (x *Scalars) GetJ() float32 {
	if x != nil {
		return x.J
	}
	return 0
}

func (x *Scalars) GetK() float64 {
	if x != nil {
		return x.K
	}
	return 0
}

func (x *Scalars) GetL() uint32 {
	if x != nil {
		return x.L
	}
	return 0
}

func (x *Scalars) GetM() uint64 {
	if x != nil {
		return x.M
	}
	return 0
}

func (x *Scalars) GetN() int32 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *Scalars) GetO() int64 {
	if x != nil {
		return x.O
	}
	return 0
}

func (x *Scalars) GetP() Color {
	if x != nil {
		return x.P
	}
	return Color_COLOR_UNSPECIFIED
}

func (x *Scalars) GetRp() []int32 {
	if x != nil {
		return x.Rp
	}
	return nil
}

func (x *Scalars) GetRs() []string {
	if x != nil {
		return x.Rs
	}
	return nil
}

func (x *Scalars) GetNested() *Nested {
	if x != nil {
		return x.Nested
	}
	return nil
}

func (x *Scalars) GetRn() []*Nested {
	if x != nil {
		return x.Rn
	}
	return nil
}

func (x *Scalars) GetMi() map[int32]int32 {
	if x != nil {
		return x.Mi
	}
	return nil
}

func (x *Scalars) GetMs() map[string]string {
	if x != nil {
		return x.Ms
	}
	return nil
}

func (x *Scalars) GetMn() map[string]*Nested {
	if x != nil {
		return x.Mn
	}
	return nil
}

func (x *Scalars) GetMc() map[uint32]Color {
	if x != nil {
		return x.Mc
	}
	return nil
}

func (x *Scalars) GetMb() map[int64]bool {
	if x != nil {
		return x.Mb
	}
	return nil
}

func (x *Scalars) GetChoice() isScalars_Choice {
	if x != nil {
		return x.Choice
	}
	return nil
}

func (x *Scalars) GetCi() int32 {
	if x != nil {
		if x, ok := x.Choice.(*Scalars_Ci); ok {
			return x.Ci
		}
	}
	return 0
}

func (x *Scalars) GetCs() string {
	if x != nil {
		if x, ok := x.Choice.(*Scalars_Cs); ok {
			return x.Cs
		}
	}
	return ""
}

func (x *Scalars) GetCn() *Nested {
	if x != nil {
		if x, ok := x.Choice.(*Scalars_Cn); ok {
			return x.Cn
		}
	}
	return nil
}

func (x *Scalars) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

type isScalars_Choice interface {
	isScalars_Choice()
}

type Scalars_Ci struct {
	Ci int32 `protobuf:"varint,26,opt,name=ci,proto3,oneof"`
}

type Scalars_Cs struct {
	Cs string `protobuf:"bytes,27,opt,name=cs,proto3,oneof"`
}

type Scalars_Cn struct {
	Cn *Nested `protobuf:"bytes,28,opt,name=cn,proto3,oneof"`
}

func (*Scalars_Ci) isScalars_Choice() {}

func (*Scalars_Cs) isScalars_Choice() {}

func (*Scalars_Cn) isScalars_Choice() {}

var File_scalars_proto protoreflect.FileDescriptor

const file_scalars_proto_rawDesc = "" +
	"\n" +
	"\rscalars.proto\x1a\x1fgoogle/protobuf/timestamp.proto\".\n" +
	"\x06Nested\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03num\x18\x02 \x01(\x05R\x03num\"\x8e\a\n" +
	"\aScalars\x12\f\n" +
	"\x01a\x18\x01 \x01(\x05R\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\x03R\x01b\x12\f\n" +
	"\x01c\x18\x03 \x01(\rR\x01c\x12\f\n" +
	"\x01d\x18\x04 \x01(\x04R\x01d\x12\f\n" +
	"\x01e\x18\x05 \x01(\x11R\x01e\x12\f\n" +
	"\x01f\x18\x06 \x01(\x12R\x01f\x12\f\n" +
	"\x01g\x18\a \x01(\bR\x01g\x12\f\n" +
	"\x01h\x18\b \x01(\tR\x01h\x12\f\n" +
	"\x01i\x18\t \x01(\fR\x01i\x12\f\n" +
	"\x01j\x18\n" +
	" \x01(\x02R\x01j\x12\f\n" +
	"\x01k\x18\v \x01(\x01R\x01k\x12\f\n" +
	"\x01l\x18\f \x01(\aR\x01l\x12\f\n" +
	"\x01m\x18\r \x01(\x06R\x01m\x12\f\n" +
	"\x01n\x18\x0e \x01(\x0fR\x01n\x12\f\n" +
	"\x01o\x18\x0f \x01(\x10R\x01o\x12\x14\n" +
	"\x01p\x18\x10 \x01(\x0e2\x06.ColorR\x01p\x12\x0e\n" +
	"\x02rp\x18\x11 \x03(\x05R\x02rp\x12\x0e\n" +
	"\x02rs\x18\x12 \x03(\tR\x02rs\x12\x1f\n" +
	"\x06nested\x18\x13 \x01(\v2\a.NestedR\x06nested\x12\x17\n" +
	"\x02rn\x18\x14 \x03(\v2\a.NestedR\x02rn\x12 \n" +
	"\x02mi\x18\x15 \x03(\v2\x10.Scalars.MiEntryR\x02mi\x12 \n" +
	"\x02ms\x18\x16 \x03(\v2\x10.Scalars.MsEntryR\x02ms\x12 \n" +
	"\x02mn\x18\x17 \x03(\v2\x10.Scalars.MnEntryR\x02mn\x12 \n" +
	"\x02mc\x18\x18 \x03(\v2\x10.Scalars.McEntryR\x02mc\x12 \n" +
	"\x02mb\x18\x19 \x03(\v2\x10.Scalars.MbEntryR\x02mb\x12\x10\n" +
	"\x02ci\x18\x1a \x01(\x05H\x00R\x02ci\x12\x10\n" +
	"\x02cs\x18\x1b \x01(\tH\x00R\x02cs\x12\x19\n" +
	"\x02cn\x18\x1c \x01(\v2\a.NestedH\x00R\x02cn\x12*\n" +
	"\x02ts\x18\x1d \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x1a5\n" +
	"\aMiEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a5\n" +
	"\aMsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\aMnEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1d\n" +
	"\x05value\x18\x02 \x01(\v2\a.NestedR\x05value:\x028\x01\x1a=\n" +
	"\aMcEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x1c\n" +
	"\x05value\x18\x02 \x01(\x0e2\x06.ColorR\x05value:\x028\x01\x1a5\n" +
	"\aMbEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x12R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01B\b\n" +
	"\x06choice*<\n" +
	"\x05Color\x12\x15\n" +
	"\x11COLOR_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03RED\x10\x01\x12\t\n" +
	"\x05GREEN\x10\x02\x12\b\n" +
	"\x04BLUE\x10\x032N\n" +
	"\rScalarService\x12\x1f\n" +
	"\tRoundtrip\x12\b.Scalars\x1a\b.Scalars\x12\x1c\n" +
	"\x05Watch\x12\a.Nested\x1a\b.Scalars0\x01B\x1fZ\x1dexample.com/jsoncheck/scalarsb\x06proto3"

var (
	file_scalars_proto_rawDescOnce sync.Once
	file_scalars_proto_rawDescData []byte
)

func file_scalars_proto_rawDescGZIP() []byte {
	file_scalars_proto_rawDescOnce.Do(func() {
		file_scalars_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scalars_proto_rawDesc), len(file_scalars_proto_rawDesc)))
	})
	return file_scalars_proto_rawDescData
}

var file_scalars_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_scalars_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_scalars_proto_goTypes = []any{
	(Color)(0),                    // 0: Color
	(*Nested)(nil),                // 1: Nested
	(*Scalars)(nil),               // 2: Scalars
	nil,                           // 3: Scalars.MiEntry
	nil,                           // 4: Scalars.MsEntry
	nil,                           // 5: Scalars.MnEntry
	nil,                           // 6: Scalars.McEntry
	nil,                           // 7: Scalars.MbEntry
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_scalars_proto_depIdxs = []int32{
	0,  // 0: Scalars.p:type_name -> Color
	1,  // 1: Scalars.nested:type_name -> Nested
	1,  // 2: Scalars.rn:type_name -> Nested
	3,  // 3: Scalars.mi:type_name -> Scalars.MiEntry
	4,  // 4: Scalars.ms:type_name -> Scalars.MsEntry
	5,  // 5: Scalars.mn:type_name -> Scalars.MnEntry
	6,  // 6: Scalars.mc:type_name -> Scalars.McEntry
	7,  // 7: Scalars.mb:type_name -> Scalars.MbEntry
	1,  // 8: Scalars.cn:type_name -> Nested
	8,  // 9: Scalars.ts:type_name -> google.protobuf.Timestamp
	1,  // 10: Scalars.MnEntry.value:type_name -> Nested
	0,  // 11: Scalars.McEntry.value:type_name -> Color
	2,  // 12: ScalarService.Roundtrip:input_type -> Scalars
	1,  // 13: ScalarService.Watch:input_type -> Nested
	2,  // 14: ScalarService.Roundtrip:output_type -> Scalars
	2,  // 15: ScalarService.Watch:output_type -> Scalars
	14, // [14:16] is the sub-list for method output_type
	12, // [12:14] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_scalars_proto_init() }
func file_scalars_proto_init() {
	if File_scalars_proto != nil {
		return
	}
	file_scalars_proto_msgTypes[1].OneofWrappers = []any{
		(*Scalars_Ci)(nil),
		(*Scalars_Cs)(nil),
		(*Scalars_Cn)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scalars_proto_rawDesc), len(file_scalars_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scalars_proto_goTypes,
		DependencyIndexes: file_scalars_proto_depIdxs,
		EnumInfos:         file_scalars_proto_enumTypes,
		MessageInfos:      file_scalars_proto_msgTypes,
	}.Build()
	File_scalars_proto = out.File
	file_scalars_proto_goTypes = nil
	file_scalars_proto_depIdxs = nil
}
