module main

// Conformance testee: speaks the protobuf conformance protocol over
// stdin/stdout. Each message is a little-endian uint32 length followed by a
// serialized ConformanceRequest; we reply with the same framing wrapping a
// ConformanceResponse. Loop until stdin EOF.
//
// The message types (Conformance*, ProtobufTestMessagesProto3_*) come from
// conf_pb.v, generated by run.sh from the upstream conformance protos.
//
// Raw byte I/O via read(2)/write(2): V's line-oriented stdin helpers mangle
// binary at newlines, so we go straight to the syscalls and loop for exact
// counts (pipes deliver partial reads/writes).

fn C.read(fd int, buf voidptr, count usize) isize
fn C.write(fd int, buf voidptr, count usize) isize

const type_proto3 = 'protobuf_test_messages.proto3.TestAllTypesProto3'

fn read_exact(n int) ?[]u8 {
	if n == 0 {
		return []u8{}
	}
	mut buf := []u8{len: n}
	mut off := 0
	for off < n {
		r := unsafe { C.read(0, &buf[off], usize(n - off)) }
		if r <= 0 {
			return none // EOF or error
		}
		off += int(r)
	}
	return buf
}

fn write_all(data []u8) {
	if data.len == 0 {
		return
	}
	mut off := 0
	for off < data.len {
		r := unsafe { C.write(1, &data[off], usize(data.len - off)) }
		if r <= 0 {
			break
		}
		off += int(r)
	}
}

fn read_len() ?u32 {
	b := read_exact(4)?
	return u32(b[0]) | (u32(b[1]) << 8) | (u32(b[2]) << 16) | (u32(b[3]) << 24)
}

fn put_len(v u32) []u8 {
	return [u8(v & 0xff), u8((v >> 8) & 0xff), u8((v >> 16) & 0xff), u8((v >> 24) & 0xff)]
}

fn skipped(s string) Conformance_ConformanceResponse {
	return Conformance_ConformanceResponse{
		result: Conformance_ConformanceResponse_Skipped{
			value: s
		}
	}
}

fn parse_error(s string) Conformance_ConformanceResponse {
	return Conformance_ConformanceResponse{
		result: Conformance_ConformanceResponse_ParseError{
			value: s
		}
	}
}

fn runtime_error(s string) Conformance_ConformanceResponse {
	return Conformance_ConformanceResponse{
		result: Conformance_ConformanceResponse_RuntimeError{
			value: s
		}
	}
}

fn handle(req Conformance_ConformanceRequest) Conformance_ConformanceResponse {
	// we implement only the proto3 message; everything else is skipped so the
	// runner counts it as unsupported rather than failed
	if req.message_type != type_proto3 {
		return skipped('unsupported message_type: ${req.message_type}')
	}
	payload := req.payload or { return runtime_error('request has no payload') }
	mut msg := ProtobufTestMessagesProto3_TestAllTypesProto3{}
	match payload {
		Conformance_ConformanceRequest_ProtobufPayload {
			msg = ProtobufTestMessagesProto3_TestAllTypesProto3.decode(payload.value) or {
				return parse_error(err.msg())
			}
		}
		Conformance_ConformanceRequest_JsonPayload {
			msg = ProtobufTestMessagesProto3_TestAllTypesProto3.from_json(payload.value) or {
				return parse_error(err.msg())
			}
		}
		else {
			return skipped('unsupported input format')
		}
	}
	match req.requested_output_format {
		.protobuf {
			return Conformance_ConformanceResponse{
				result: Conformance_ConformanceResponse_ProtobufPayload{
					value: msg.encode()
				}
			}
		}
		.json {
			return Conformance_ConformanceResponse{
				result: Conformance_ConformanceResponse_JsonPayload{
					value: msg.json()
				}
			}
		}
		else {
			return skipped('unsupported output format')
		}
	}
}

fn main() {
	for {
		n := read_len() or { break } // clean EOF between messages
		reqbytes := read_exact(int(n)) or { break }
		resp := if req := Conformance_ConformanceRequest.decode(reqbytes) {
			handle(req)
		} else {
			runtime_error('request decode failed: ${err.msg()}')
		}
		out := resp.encode()
		write_all(put_len(u32(out.len)))
		write_all(out)
	}
}
