// Code generated by protobuf.gen. DO NOT EDIT.
module main

import protobuf

pub enum Person_PhoneType {
	phone_type_unspecified = 0
	phone_type_mobile      = 1
	phone_type_home        = 2
	phone_type_work        = 3
}

pub struct Person {
pub mut:
	name   string
	id     int
	email  string
	phones []Person_PhoneNumber
}

pub fn (m Person) encode() []u8 {
	mut e := protobuf.Encoder{}
	if m.name != '' {
		e.write_string_field(1, m.name)
	}
	if m.id != 0 {
		e.write_int32_field(2, m.id)
	}
	if m.email != '' {
		e.write_string_field(3, m.email)
	}
	for v in m.phones {
		e.write_message_field(4, v.encode())
	}
	return e.buf
}

pub fn Person.decode(buf []u8) !Person {
	mut m := Person{}
	mut d := protobuf.Decoder{
		buf: buf
	}
	for d.more() {
		field, wt := d.read_tag()!
		match field {
			1 {
				m.name = d.read_string()!
			}
			2 {
				m.id = d.read_int32()!
			}
			3 {
				m.email = d.read_string()!
			}
			4 {
				m.phones << Person_PhoneNumber.decode(d.read_bytes()!)!
			}
			else {
				d.skip(wt)!
			}
		}
	}
	return m
}

pub struct Person_PhoneNumber {
pub mut:
	number string
	type_  Person_PhoneType
}

pub fn (m Person_PhoneNumber) encode() []u8 {
	mut e := protobuf.Encoder{}
	if m.number != '' {
		e.write_string_field(1, m.number)
	}
	if int(m.type_) != 0 {
		e.write_int32_field(2, int(m.type_))
	}
	return e.buf
}

pub fn Person_PhoneNumber.decode(buf []u8) !Person_PhoneNumber {
	mut m := Person_PhoneNumber{}
	mut d := protobuf.Decoder{
		buf: buf
	}
	for d.more() {
		field, wt := d.read_tag()!
		match field {
			1 {
				m.number = d.read_string()!
			}
			2 {
				m.type_ = unsafe { Person_PhoneType(d.read_int32()!) }
			}
			else {
				d.skip(wt)!
			}
		}
	}
	return m
}

pub struct AddressBook {
pub mut:
	people []Person
}

pub fn (m AddressBook) encode() []u8 {
	mut e := protobuf.Encoder{}
	for v in m.people {
		e.write_message_field(1, v.encode())
	}
	return e.buf
}

pub fn AddressBook.decode(buf []u8) !AddressBook {
	mut m := AddressBook{}
	mut d := protobuf.Decoder{
		buf: buf
	}
	for d.more() {
		field, wt := d.read_tag()!
		match field {
			1 {
				m.people << Person.decode(d.read_bytes()!)!
			}
			else {
				d.skip(wt)!
			}
		}
	}
	return m
}
