// Code generated by protobuf.gen. DO NOT EDIT.
module main

import protobuf

pub enum Person_PhoneType {
	phone_type_unspecified = 0
	phone_type_mobile      = 1
	phone_type_home        = 2
	phone_type_work        = 3
}

pub struct Person {
pub mut:
	name       string
	id         int
	email      string
	phones     []Person_PhoneNumber
	pb_unknown []u8 // unrecognized fields, re-emitted on encode
}

pub fn (m &Person) encoded_size() int {
	mut n := 0
	if m.name != '' {
		n += protobuf.len_field_len(1, m.name.len)
	}
	if m.id != 0 {
		n += protobuf.tag_len(2) + protobuf.varint_len(protobuf.int32_wire(m.id))
	}
	if m.email != '' {
		n += protobuf.len_field_len(3, m.email.len)
	}
	for v in m.phones {
		n += protobuf.len_field_len(4, v.encoded_size())
	}
	return n + m.pb_unknown.len
}

pub fn (m &Person) encode_to(mut e protobuf.Encoder) {
	if m.name != '' {
		e.write_string_field(1, m.name)
	}
	if m.id != 0 {
		e.write_int32_field(2, m.id)
	}
	if m.email != '' {
		e.write_string_field(3, m.email)
	}
	for v in m.phones {
		e.write_tag(4, .len_delim)
		e.write_varint(u64(v.encoded_size()))
		v.encode_to(mut e)
	}
	e.write_raw(m.pb_unknown)
}

pub fn (m &Person) encode() []u8 {
	mut e := protobuf.Encoder{
		buf: []u8{cap: m.encoded_size()}
	}
	m.encode_to(mut e)
	return e.buf
}

pub fn Person.decode(buf []u8) !Person {
	mut m := Person{}
	mut d := protobuf.Decoder{
		buf: buf
	}
	for d.more() {
		tag_start := d.pos
		field, wt := d.read_tag()!
		match field {
			1 {
				m.name = d.read_string()!
			}
			2 {
				m.id = d.read_int32()!
			}
			3 {
				m.email = d.read_string()!
			}
			4 {
				m.phones << Person_PhoneNumber.decode(d.read_view()!)!
			}
			else {
				d.skip(wt)!
				m.pb_unknown << d.buf[tag_start..d.pos]
			}
		}
	}
	return m
}

pub struct Person_PhoneNumber {
pub mut:
	number     string
	type_      Person_PhoneType
	pb_unknown []u8 // unrecognized fields, re-emitted on encode
}

pub fn (m &Person_PhoneNumber) encoded_size() int {
	mut n := 0
	if m.number != '' {
		n += protobuf.len_field_len(1, m.number.len)
	}
	if int(m.type_) != 0 {
		n += protobuf.tag_len(2) + protobuf.varint_len(protobuf.int32_wire(int(m.type_)))
	}
	return n + m.pb_unknown.len
}

pub fn (m &Person_PhoneNumber) encode_to(mut e protobuf.Encoder) {
	if m.number != '' {
		e.write_string_field(1, m.number)
	}
	if int(m.type_) != 0 {
		e.write_int32_field(2, int(m.type_))
	}
	e.write_raw(m.pb_unknown)
}

pub fn (m &Person_PhoneNumber) encode() []u8 {
	mut e := protobuf.Encoder{
		buf: []u8{cap: m.encoded_size()}
	}
	m.encode_to(mut e)
	return e.buf
}

pub fn Person_PhoneNumber.decode(buf []u8) !Person_PhoneNumber {
	mut m := Person_PhoneNumber{}
	mut d := protobuf.Decoder{
		buf: buf
	}
	for d.more() {
		tag_start := d.pos
		field, wt := d.read_tag()!
		match field {
			1 {
				m.number = d.read_string()!
			}
			2 {
				m.type_ = unsafe { Person_PhoneType(d.read_int32()!) }
			}
			else {
				d.skip(wt)!
				m.pb_unknown << d.buf[tag_start..d.pos]
			}
		}
	}
	return m
}

pub struct AddressBook {
pub mut:
	people     []Person
	pb_unknown []u8 // unrecognized fields, re-emitted on encode
}

pub fn (m &AddressBook) encoded_size() int {
	mut n := 0
	for v in m.people {
		n += protobuf.len_field_len(1, v.encoded_size())
	}
	return n + m.pb_unknown.len
}

pub fn (m &AddressBook) encode_to(mut e protobuf.Encoder) {
	for v in m.people {
		e.write_tag(1, .len_delim)
		e.write_varint(u64(v.encoded_size()))
		v.encode_to(mut e)
	}
	e.write_raw(m.pb_unknown)
}

pub fn (m &AddressBook) encode() []u8 {
	mut e := protobuf.Encoder{
		buf: []u8{cap: m.encoded_size()}
	}
	m.encode_to(mut e)
	return e.buf
}

pub fn AddressBook.decode(buf []u8) !AddressBook {
	mut m := AddressBook{}
	mut d := protobuf.Decoder{
		buf: buf
	}
	for d.more() {
		tag_start := d.pos
		field, wt := d.read_tag()!
		match field {
			1 {
				m.people << Person.decode(d.read_view()!)!
			}
			else {
				d.skip(wt)!
				m.pb_unknown << d.buf[tag_start..d.pos]
			}
		}
	}
	return m
}
