// Address book CLI storing contacts as a proto3 AddressBook binary —
// the same file protoc and every other protobuf implementation can read.
// Types + wire code live in addressbook_pb.v, generated by vpbgen:
//   v run cmd/vpbgen -m main -o examples/addressbook/addressbook_pb.v examples/addressbook/addressbook.proto
//
//   v run . add "Ada Lovelace" --email ada@analytical.uk --mobile +44-555-0100
//   v run . list
//   protoc --decode=tutorial.AddressBook addressbook.proto < addressbook.bin
module main

import os

fn load(path string) !AddressBook {
	if !os.exists(path) {
		return AddressBook{}
	}
	return AddressBook.decode(os.read_bytes(path)!)!
}

fn usage() {
	eprintln('usage: addressbook [--db file] add <name> [--id N] [--email E] [--mobile P] [--home P] [--work P]')
	eprintln('       addressbook [--db file] list')
	exit(1)
}

fn flag_val(args []string, i int) string {
	if i + 1 >= args.len {
		usage()
	}
	return args[i + 1]
}

fn main() {
	mut args := os.args[1..].clone()
	mut db := 'addressbook.bin'
	for i, arg in args {
		if arg == '--db' {
			db = flag_val(args, i)
			args.delete(i)
			args.delete(i)
			break
		}
	}
	if args.len == 0 {
		usage()
	}
	mut book := load(db) or {
		eprintln('cannot read ${db}: ${err}')
		exit(1)
	}
	match args[0] {
		'add' {
			if args.len < 2 {
				usage()
			}
			mut p := Person{
				name: args[1]
			}
			mut i := 2
			for i < args.len {
				match args[i] {
					'--id' { p.id = flag_val(args, i).int() }
					'--email' { p.email = flag_val(args, i) }
					'--mobile' { p.phones << Person_PhoneNumber{flag_val(args, i), .phone_type_mobile} }
					'--home' { p.phones << Person_PhoneNumber{flag_val(args, i), .phone_type_home} }
					'--work' { p.phones << Person_PhoneNumber{flag_val(args, i), .phone_type_work} }
					else { usage() }
				}
				i += 2
			}
			if p.id == 0 {
				mut max := 0
				for q in book.people {
					if q.id > max {
						max = q.id
					}
				}
				p.id = max + 1
			}
			book.people << p
			os.write_file_array(db, book.encode()) or {
				eprintln('cannot write ${db}: ${err}')
				exit(1)
			}
			println('added #${p.id} ${p.name} (${os.file_size(db)} bytes total)')
		}
		'list' {
			if book.people.len == 0 {
				println('address book is empty')
				return
			}
			for p in book.people {
				email := if p.email != '' { ' <${p.email}>' } else { '' }
				println('#${p.id}  ${p.name}${email}')
				for ph in p.phones {
					label := ph.type_.str().trim_string_left('phone_type_')
					println('     ${label}: ${ph.number}')
				}
			}
		}
		else {
			usage()
		}
	}
}
