// Interop harness, driven by run.sh:
//   gen <dir> <count> <seed>    encode known + fuzzed Scalars to <dir>
//   check <dir> <count> <seed>  decode protoc's re-encodings, compare
// check regenerates the same PRNG sequence, so any drift between what we
// encoded and what protoc round-tripped shows up as a value or byte diff.
//
// Scalars/Nested/Color come from scalars_pb.v — GENERATED by vpbgen from
// scalars.proto — so this oracle validates the code generator, not
// hand-written wire calls. run.sh fails if scalars_pb.v is stale.
module main

import os

struct Rng {
mut:
	state u64
}

fn (mut r Rng) next() u64 {
	r.state += u64(0x9E3779B97F4A7C15)
	mut z := r.state
	z = (z ^ (z >> 30)) * u64(0xBF58476D1CE4E5B9)
	z = (z ^ (z >> 27)) * u64(0x94D049BB133111EB)
	return z ^ (z >> 31)
}

fn (mut r Rng) below(n int) int {
	return int(r.next() % u64(n))
}

fn (mut r Rng) chance(pct int) bool {
	return r.below(100) < pct
}

const tricky_i32 = [0, 1, -1, 127, 128, 300, 2147483647, -2147483648, 1000000, -1000000]
const tricky_i64 = [i64(0), 1, -1, 300, 9223372036854775807, i64(-9223372036854775807) - 1,
	123456789012345, -123456789012345]
const tricky_u32 = [u32(0), 1, 127, 128, 4294967295, 65536]
const tricky_u64 = [u64(0), 1, 18446744073709551615, 4294967296]
const string_pool = ['', 'a', 'hello', 'héllo wörld', '🚀🌍', '日本語テキスト',
	'line\nbreak', 'tab\there', 'quote"and\'quote']

fn (mut r Rng) i32val() int {
	return tricky_i32[r.below(tricky_i32.len)]
}

fn (mut r Rng) i64val() i64 {
	return tricky_i64[r.below(tricky_i64.len)]
}

fn (mut r Rng) strval() string {
	return string_pool[r.below(string_pool.len)]
}

fn gen_nested(mut r Rng) Nested {
	return Nested{
		name: r.strval()
		num:  r.i32val()
	}
}

fn gen_scalars(mut r Rng) Scalars {
	mut s := Scalars{}
	if r.chance(60) {
		s.a = r.i32val()
	}
	if r.chance(60) {
		s.b = r.i64val()
	}
	if r.chance(60) {
		s.c = tricky_u32[r.below(tricky_u32.len)]
	}
	if r.chance(60) {
		s.d = tricky_u64[r.below(tricky_u64.len)]
	}
	if r.chance(60) {
		s.e = r.i32val()
	}
	if r.chance(60) {
		s.f = r.i64val()
	}
	if r.chance(60) {
		s.g = true
	}
	if r.chance(60) {
		s.h = r.strval()
	}
	if r.chance(60) {
		n := r.below(20)
		for _ in 0 .. n {
			s.i << u8(r.next())
		}
	}
	// floats built from small ints over powers of two stay exact in
	// binary, text format, and back
	if r.chance(60) {
		s.j = f32(r.below(2000) - 1000) / f32(16.0)
	}
	if r.chance(60) {
		s.k = f64(r.below(2000000) - 1000000) / 64.0
	}
	if r.chance(60) {
		s.l = tricky_u32[r.below(tricky_u32.len)]
	}
	if r.chance(60) {
		s.m = tricky_u64[r.below(tricky_u64.len)]
	}
	if r.chance(60) {
		s.n = r.i32val()
	}
	if r.chance(60) {
		s.o = r.i64val()
	}
	if r.chance(60) {
		s.p = unsafe { Color(r.below(4)) }
	}
	if r.chance(50) {
		for _ in 0 .. r.below(6) {
			s.rp << r.i32val()
		}
	}
	if r.chance(50) {
		for _ in 0 .. r.below(4) {
			s.rs << r.strval()
		}
	}
	if r.chance(50) {
		s.nested = gen_nested(mut r)
	}
	if r.chance(40) {
		for _ in 0 .. r.below(3) {
			s.rn << gen_nested(mut r)
		}
	}
	if r.chance(50) {
		for _ in 0 .. r.below(4) {
			s.mi[r.i32val()] = r.i32val()
		}
	}
	if r.chance(50) {
		for _ in 0 .. r.below(4) {
			s.ms[r.strval()] = r.strval()
		}
	}
	if r.chance(40) {
		for _ in 0 .. r.below(3) {
			s.mn[r.strval()] = gen_nested(mut r)
		}
	}
	if r.chance(40) {
		for _ in 0 .. r.below(3) {
			s.mc[tricky_u32[r.below(tricky_u32.len)]] = unsafe { Color(r.below(4)) }
		}
	}
	if r.chance(40) {
		for _ in 0 .. r.below(3) {
			s.mb[r.i64val()] = r.chance(50)
		}
	}
	if r.chance(60) {
		match r.below(3) {
			0 {
				s.choice = Scalars_Ci{
					value: r.i32val()
				}
			}
			1 {
				s.choice = Scalars_Cs{
					value: r.strval()
				}
			}
			else {
				s.choice = Scalars_Cn{
					value: gen_nested(mut r)
				}
			}
		}
	}
	return s
}

// Every field at an extreme value, plus an intentionally empty nested
// message in rn (empty messages still encode as LEN 0 under proto3).
fn known_scalars() Scalars {
	mut s := known_scalars_base()
	// map extremes: zero key + zero value entries still encode both fields,
	// empty message values encode as LEN 0, i64 min/max keys sort signed
	s.mi = {
		-2147483648: -1
		0:           0
		2147483647:  150
	}
	s.ms = {
		'':  ''
		'k': 'héllo'
	}
	s.mn = {
		'a': Nested{}
		'b': Nested{
			name: 'x'
			num:  -1
		}
	}
	s.mc = {
		u32(0):          Color.blue
		u32(4294967295): Color.color_unspecified
	}
	s.mb[i64(-9223372036854775807) - 1] = true
	s.mb[i64(9223372036854775807)] = false
	// empty-string arm: oneof presence at the zero value
	s.choice = Scalars_Cs{
		value: ''
	}
	return s
}

fn known_scalars_base() Scalars {
	return Scalars{
		a:      -1
		b:      i64(-9223372036854775807) - 1
		c:      4294967295
		d:      18446744073709551615
		e:      -2147483648
		f:      i64(-9223372036854775807) - 1
		g:      true
		h:      'héllo 🌍 wörld'
		i:      [u8(0), 1, 255, 0, 127]
		j:      1.5
		k:      3.141592653589793
		l:      u32(0xDEADBEEF)
		m:      u64(0x0123456789ABCDEF)
		n:      -1
		o:      i64(-9223372036854775807) - 1
		p:      .blue
		rp:     [0, -1, 2147483647, -2147483648, 150]
		rs:     ['', 'a', '🚀']
		nested: Nested{
			name: 'nested'
			num:  150
		}
		rn:     [Nested{}, Nested{
			name: 'x'
		}]
	}
}

fn eq(a Scalars, b Scalars) bool {
	return a == b
}

fn fail(msg string) {
	eprintln('FAIL: ${msg}')
	exit(1)
}

fn main() {
	if os.args.len < 5 {
		fail('usage: harness <gen|check> <dir> <count> <seed>')
	}
	mode := os.args[1]
	dir := os.args[2]
	count := os.args[3].int()
	seed := os.args[4].u64()
	mut r := Rng{
		state: seed
	}
	match mode {
		'gen' {
			os.write_file_array('${dir}/known.bin', known_scalars().encode())!
			for i in 0 .. count {
				os.write_file_array('${dir}/fuzz_${i}.bin', gen_scalars(mut r).encode())!
			}
			println('generated ${count} fuzz messages + known.bin')
		}
		'check' {
			known_pb := os.read_bytes('${dir}/known.protoc.bin')!
			known_dec := Scalars.decode(known_pb)!
			if !eq(known_dec, known_scalars()) {
				fail('known: decode of protoc bytes != expected struct')
			}
			if known_dec.encode() != known_pb {
				fail('known: re-encode != protoc bytes')
			}
			for i in 0 .. count {
				want := gen_scalars(mut r)
				pb := os.read_bytes('${dir}/fuzz_${i}.protoc.bin')!
				got := Scalars.decode(pb)!
				if !eq(got, want) {
					fail('fuzz_${i}: decode of protoc bytes != generated struct\nwant: ${want}\ngot:  ${got}')
				}
				if got.encode() != pb {
					fail('fuzz_${i}: re-encode != protoc bytes')
				}
			}
			println('checked ${count} fuzz messages + known.bin against protoc')
		}
		else {
			fail('unknown mode ${mode}')
		}
	}
}
