// Code generated by protobuf.gen. DO NOT EDIT.
module main

import json2
import protobuf
import time

pub enum Color {
	color_unspecified = 0
	red               = 1
	green             = 2
	blue              = 3
}

fn color_to_json(v Color) json2.Any {
	return match int(v) {
		0 { json2.Any('COLOR_UNSPECIFIED') }
		1 { json2.Any('RED') }
		2 { json2.Any('GREEN') }
		3 { json2.Any('BLUE') }
		else { json2.Any(i64(int(v))) }
	}
}

fn color_from_json(a json2.Any) !Color {
	if a is string {
		match a {
			'COLOR_UNSPECIFIED' { return unsafe { Color(0) } }
			'RED' { return unsafe { Color(1) } }
			'GREEN' { return unsafe { Color(2) } }
			'BLUE' { return unsafe { Color(3) } }
			else { return error('protojson: unknown value `${a}` for Color') }
		}
	}
	return unsafe { Color(int(protobuf.json_intv(a)!)) }
}

pub struct Nested {
pub mut:
	name       string
	num        int
	pb_unknown []u8 // unrecognized fields, re-emitted on encode
}

pub fn (m &Nested) encoded_size() int {
	mut n := 0
	if m.name != '' {
		n += protobuf.len_field_len(1, m.name.len)
	}
	if m.num != 0 {
		n += protobuf.tag_len(2) + protobuf.varint_len(u64(i64(m.num)))
	}
	return n + m.pb_unknown.len
}

pub fn (m &Nested) encode_to(mut e protobuf.Encoder) {
	if m.name != '' {
		e.write_string_field(1, m.name)
	}
	if m.num != 0 {
		e.write_int32_field(2, m.num)
	}
	e.write_raw(m.pb_unknown)
}

pub fn (m &Nested) encode() []u8 {
	mut e := protobuf.Encoder{
		buf: []u8{cap: m.encoded_size()}
	}
	m.encode_to(mut e)
	return e.buf
}

pub fn Nested.decode(buf []u8) !Nested {
	mut m := Nested{}
	mut d := protobuf.Decoder{
		buf: buf
	}
	for d.more() {
		tag_start := d.pos
		field, wt := d.read_tag()!
		match field {
			1 {
				m.name = d.read_string()!
			}
			2 {
				m.num = d.read_int32()!
			}
			else {
				d.skip(wt)!
				m.pb_unknown << d.buf[tag_start..d.pos]
			}
		}
	}
	return m
}

pub fn (m &Nested) json() string {
	return m.json_value().json_str()
}

pub fn Nested.from_json(s string) !Nested {
	return Nested.from_json_value(protobuf.json_parse(s)!)
}

pub fn (m &Nested) json_value() json2.Any {
	mut o := map[string]json2.Any{}
	if m.name != '' {
		o['name'] = json2.Any(m.name)
	}
	if m.num != 0 {
		o['num'] = json2.Any(i64(m.num))
	}
	return json2.Any(o)
}

pub fn Nested.from_json_value(a json2.Any) !Nested {
	obj := protobuf.json_object(a)!
	mut m := Nested{}
	for jk, jv in obj {
		if jv is json2.Null {
			continue
		}
		match jk {
			'name' {
				m.name = protobuf.json_stringv(jv)!
			}
			'num' {
				m.num = protobuf.json_int32v(jv)!
			}
			else {}
		}
	}
	return m
}

pub struct Scalars_Ci {
pub mut:
	value int
}

pub struct Scalars_Cs {
pub mut:
	value string
}

pub struct Scalars_Cn {
pub mut:
	value Nested
}

pub type Scalars_Choice = Scalars_Ci | Scalars_Cs | Scalars_Cn

pub struct Scalars {
pub mut:
	a          int
	b          i64
	c          u32
	d          u64
	e          int
	f          i64
	g          bool
	h          string
	i          []u8
	j          f32
	k          f64
	l          u32
	m          u64
	n          int
	o          i64
	p          Color
	rp         []int
	rs         []string
	nested     ?Nested
	rn         []Nested
	mi         map[int]int
	ms         map[string]string
	mn         map[string]Nested
	mc         map[u32]Color
	mb         map[i64]bool
	choice     ?Scalars_Choice
	ts         ?GoogleProtobuf_Timestamp
	pb_unknown []u8 // unrecognized fields, re-emitted on encode
}

pub fn (m &Scalars) encoded_size() int {
	mut n := 0
	if m.a != 0 {
		n += protobuf.tag_len(1) + protobuf.varint_len(u64(i64(m.a)))
	}
	if m.b != 0 {
		n += protobuf.tag_len(2) + protobuf.varint_len(u64(m.b))
	}
	if m.c != 0 {
		n += protobuf.tag_len(3) + protobuf.varint_len(u64(m.c))
	}
	if m.d != 0 {
		n += protobuf.tag_len(4) + protobuf.varint_len(m.d)
	}
	if m.e != 0 {
		n += protobuf.tag_len(5) + protobuf.varint_len(protobuf.zigzag_encode(i64(m.e)))
	}
	if m.f != 0 {
		n += protobuf.tag_len(6) + protobuf.varint_len(protobuf.zigzag_encode(m.f))
	}
	if m.g {
		n += protobuf.tag_len(7) + 1
	}
	if m.h != '' {
		n += protobuf.len_field_len(8, m.h.len)
	}
	if m.i.len > 0 {
		n += protobuf.len_field_len(9, m.i.len)
	}
	if m.j != 0 {
		n += protobuf.tag_len(10) + 4
	}
	if m.k != 0 {
		n += protobuf.tag_len(11) + 8
	}
	if m.l != 0 {
		n += protobuf.tag_len(12) + 4
	}
	if m.m != 0 {
		n += protobuf.tag_len(13) + 8
	}
	if m.n != 0 {
		n += protobuf.tag_len(14) + 4
	}
	if m.o != 0 {
		n += protobuf.tag_len(15) + 8
	}
	if int(m.p) != 0 {
		n += protobuf.tag_len(16) + protobuf.varint_len(u64(i64(int(m.p))))
	}
	if m.rp.len > 0 {
		mut p := 0
		for v in m.rp {
			p += protobuf.varint_len(u64(i64(v)))
		}
		n += protobuf.len_field_len(17, p)
	}
	for v in m.rs {
		n += protobuf.len_field_len(18, v.len)
	}
	if nested := m.nested {
		n += protobuf.len_field_len(19, nested.encoded_size())
	}
	for v in m.rn {
		n += protobuf.len_field_len(20, v.encoded_size())
	}
	for k, v in m.mi {
		n += protobuf.len_field_len(21, protobuf.tag_len(1) + protobuf.varint_len(u64(i64(k))) +
			protobuf.tag_len(2) + protobuf.varint_len(u64(i64(v))))
	}
	for k, v in m.ms {
		n += protobuf.len_field_len(22, protobuf.len_field_len(1, k.len) +
			protobuf.len_field_len(2, v.len))
	}
	for k, v in m.mn {
		n += protobuf.len_field_len(23, protobuf.len_field_len(1, k.len) +
			protobuf.len_field_len(2, v.encoded_size()))
	}
	for k, v in m.mc {
		n += protobuf.len_field_len(24, protobuf.tag_len(1) + protobuf.varint_len(u64(k)) +
			protobuf.tag_len(2) + protobuf.varint_len(u64(i64(int(v)))))
	}
	for k, _ in m.mb {
		n += protobuf.len_field_len(25, protobuf.tag_len(1) +
			protobuf.varint_len(protobuf.zigzag_encode(k)) + protobuf.tag_len(2) + 1)
	}
	if ov := m.choice {
		if ov is Scalars_Ci {
			n += protobuf.tag_len(26) + protobuf.varint_len(u64(i64(ov.value)))
		}
	}
	if ov := m.choice {
		if ov is Scalars_Cs {
			n += protobuf.len_field_len(27, ov.value.len)
		}
	}
	if ov := m.choice {
		if ov is Scalars_Cn {
			n += protobuf.len_field_len(28, ov.value.encoded_size())
		}
	}
	if ts := m.ts {
		n += protobuf.len_field_len(29, ts.encoded_size())
	}
	return n + m.pb_unknown.len
}

pub fn (m &Scalars) encode_to(mut e protobuf.Encoder) {
	if m.a != 0 {
		e.write_int32_field(1, m.a)
	}
	if m.b != 0 {
		e.write_int64_field(2, m.b)
	}
	if m.c != 0 {
		e.write_uint32_field(3, m.c)
	}
	if m.d != 0 {
		e.write_uint64_field(4, m.d)
	}
	if m.e != 0 {
		e.write_sint32_field(5, m.e)
	}
	if m.f != 0 {
		e.write_sint64_field(6, m.f)
	}
	if m.g {
		e.write_bool_field(7, m.g)
	}
	if m.h != '' {
		e.write_string_field(8, m.h)
	}
	if m.i.len > 0 {
		e.write_bytes_field(9, m.i)
	}
	if m.j != 0 {
		e.write_float_field(10, m.j)
	}
	if m.k != 0 {
		e.write_double_field(11, m.k)
	}
	if m.l != 0 {
		e.write_fixed32_field(12, m.l)
	}
	if m.m != 0 {
		e.write_fixed64_field(13, m.m)
	}
	if m.n != 0 {
		e.write_sfixed32_field(14, m.n)
	}
	if m.o != 0 {
		e.write_sfixed64_field(15, m.o)
	}
	if int(m.p) != 0 {
		e.write_int32_field(16, int(m.p))
	}
	if m.rp.len > 0 {
		mut p := 0
		for v in m.rp {
			p += protobuf.varint_len(u64(i64(v)))
		}
		e.write_tag(17, .len_delim)
		e.write_varint(u64(p))
		for v in m.rp {
			e.write_varint(u64(i64(v)))
		}
	}
	for v in m.rs {
		e.write_string_field(18, v)
	}
	if nested := m.nested {
		e.write_tag(19, .len_delim)
		e.write_varint(u64(nested.encoded_size()))
		nested.encode_to(mut e)
	}
	for v in m.rn {
		e.write_tag(20, .len_delim)
		e.write_varint(u64(v.encoded_size()))
		v.encode_to(mut e)
	}
	if m.mi.len > 0 {
		mut mi_keys := m.mi.keys()
		mi_keys.sort()
		for k in mi_keys {
			v := m.mi[k]
			e.write_tag(21, .len_delim)
			e.write_varint(u64(protobuf.tag_len(1) + protobuf.varint_len(u64(i64(k))) +
				protobuf.tag_len(2) + protobuf.varint_len(u64(i64(v)))))
			e.write_int32_field(1, k)
			e.write_int32_field(2, v)
		}
	}
	if m.ms.len > 0 {
		mut ms_keys := m.ms.keys()
		ms_keys.sort()
		for k in ms_keys {
			v := m.ms[k]
			e.write_tag(22, .len_delim)
			e.write_varint(u64(protobuf.len_field_len(1, k.len) + protobuf.len_field_len(2, v.len)))
			e.write_string_field(1, k)
			e.write_string_field(2, v)
		}
	}
	if m.mn.len > 0 {
		mut mn_keys := m.mn.keys()
		mn_keys.sort()
		for k in mn_keys {
			v := m.mn[k]
			e.write_tag(23, .len_delim)
			e.write_varint(u64(protobuf.len_field_len(1, k.len) +
				protobuf.len_field_len(2, v.encoded_size())))
			e.write_string_field(1, k)
			e.write_tag(2, .len_delim)
			e.write_varint(u64(v.encoded_size()))
			v.encode_to(mut e)
		}
	}
	if m.mc.len > 0 {
		mut mc_keys := m.mc.keys()
		mc_keys.sort()
		for k in mc_keys {
			v := m.mc[k]
			e.write_tag(24, .len_delim)
			e.write_varint(u64(protobuf.tag_len(1) + protobuf.varint_len(u64(k)) +
				protobuf.tag_len(2) + protobuf.varint_len(u64(i64(int(v))))))
			e.write_uint32_field(1, k)
			e.write_int32_field(2, int(v))
		}
	}
	if m.mb.len > 0 {
		mut mb_keys := m.mb.keys()
		mb_keys.sort()
		for k in mb_keys {
			v := m.mb[k]
			e.write_tag(25, .len_delim)
			e.write_varint(u64(protobuf.tag_len(1) +
				protobuf.varint_len(protobuf.zigzag_encode(k)) + protobuf.tag_len(2) + 1))
			e.write_sint64_field(1, k)
			e.write_bool_field(2, v)
		}
	}
	if ov := m.choice {
		if ov is Scalars_Ci {
			e.write_int32_field(26, ov.value)
		}
	}
	if ov := m.choice {
		if ov is Scalars_Cs {
			e.write_string_field(27, ov.value)
		}
	}
	if ov := m.choice {
		if ov is Scalars_Cn {
			e.write_tag(28, .len_delim)
			e.write_varint(u64(ov.value.encoded_size()))
			ov.value.encode_to(mut e)
		}
	}
	if ts := m.ts {
		e.write_tag(29, .len_delim)
		e.write_varint(u64(ts.encoded_size()))
		ts.encode_to(mut e)
	}
	e.write_raw(m.pb_unknown)
}

pub fn (m &Scalars) encode() []u8 {
	mut e := protobuf.Encoder{
		buf: []u8{cap: m.encoded_size()}
	}
	m.encode_to(mut e)
	return e.buf
}

pub fn Scalars.decode(buf []u8) !Scalars {
	mut m := Scalars{}
	mut d := protobuf.Decoder{
		buf: buf
	}
	for d.more() {
		tag_start := d.pos
		field, wt := d.read_tag()!
		match field {
			1 {
				m.a = d.read_int32()!
			}
			2 {
				m.b = d.read_int64()!
			}
			3 {
				m.c = d.read_uint32()!
			}
			4 {
				m.d = d.read_uint64()!
			}
			5 {
				m.e = d.read_sint32()!
			}
			6 {
				m.f = d.read_sint64()!
			}
			7 {
				m.g = d.read_bool()!
			}
			8 {
				m.h = d.read_string()!
			}
			9 {
				m.i = d.read_bytes()!
			}
			10 {
				m.j = d.read_float()!
			}
			11 {
				m.k = d.read_double()!
			}
			12 {
				m.l = d.read_fixed32()!
			}
			13 {
				m.m = d.read_fixed64()!
			}
			14 {
				m.n = d.read_sfixed32()!
			}
			15 {
				m.o = d.read_sfixed64()!
			}
			16 {
				m.p = unsafe { Color(d.read_int32()!) }
			}
			17 {
				if wt == .len_delim {
					mut sub := protobuf.Decoder{
						buf: d.read_view()!
					}
					for sub.more() {
						m.rp << sub.read_int32()!
					}
				} else {
					m.rp << d.read_int32()!
				}
			}
			18 {
				m.rs << d.read_string()!
			}
			19 {
				m.nested = Nested.decode(d.read_view()!)!
			}
			20 {
				m.rn << Nested.decode(d.read_view()!)!
			}
			21 {
				mut sub := protobuf.Decoder{
					buf: d.read_view()!
				}
				mut mk := 0
				mut mv := 0
				for sub.more() {
					mf, mw := sub.read_tag()!
					match mf {
						1 { mk = sub.read_int32()! }
						2 { mv = sub.read_int32()! }
						else { sub.skip(mw)! }
					}
				}
				m.mi[mk] = mv
			}
			22 {
				mut sub := protobuf.Decoder{
					buf: d.read_view()!
				}
				mut mk := ''
				mut mv := ''
				for sub.more() {
					mf, mw := sub.read_tag()!
					match mf {
						1 { mk = sub.read_string()! }
						2 { mv = sub.read_string()! }
						else { sub.skip(mw)! }
					}
				}
				m.ms[mk] = mv
			}
			23 {
				mut sub := protobuf.Decoder{
					buf: d.read_view()!
				}
				mut mk := ''
				mut mv := Nested{}
				for sub.more() {
					mf, mw := sub.read_tag()!
					match mf {
						1 { mk = sub.read_string()! }
						2 { mv = Nested.decode(sub.read_view()!)! }
						else { sub.skip(mw)! }
					}
				}
				m.mn[mk] = mv
			}
			24 {
				mut sub := protobuf.Decoder{
					buf: d.read_view()!
				}
				mut mk := u32(0)
				mut mv := unsafe { Color(0) }
				for sub.more() {
					mf, mw := sub.read_tag()!
					match mf {
						1 { mk = sub.read_uint32()! }
						2 { mv = unsafe { Color(sub.read_int32()!) } }
						else { sub.skip(mw)! }
					}
				}
				m.mc[mk] = mv
			}
			25 {
				mut sub := protobuf.Decoder{
					buf: d.read_view()!
				}
				mut mk := i64(0)
				mut mv := false
				for sub.more() {
					mf, mw := sub.read_tag()!
					match mf {
						1 { mk = sub.read_sint64()! }
						2 { mv = sub.read_bool()! }
						else { sub.skip(mw)! }
					}
				}
				m.mb[mk] = mv
			}
			26 {
				m.choice = Scalars_Ci{
					value: d.read_int32()!
				}
			}
			27 {
				m.choice = Scalars_Cs{
					value: d.read_string()!
				}
			}
			28 {
				m.choice = Scalars_Cn{
					value: Nested.decode(d.read_view()!)!
				}
			}
			29 {
				m.ts = GoogleProtobuf_Timestamp.decode(d.read_view()!)!
			}
			else {
				d.skip(wt)!
				m.pb_unknown << d.buf[tag_start..d.pos]
			}
		}
	}
	return m
}

pub fn (m &Scalars) json() string {
	return m.json_value().json_str()
}

pub fn Scalars.from_json(s string) !Scalars {
	return Scalars.from_json_value(protobuf.json_parse(s)!)
}

pub fn (m &Scalars) json_value() json2.Any {
	mut o := map[string]json2.Any{}
	if m.a != 0 {
		o['a'] = json2.Any(i64(m.a))
	}
	if m.b != 0 {
		o['b'] = protobuf.json_i64(m.b)
	}
	if m.c != 0 {
		o['c'] = json2.Any(u64(m.c))
	}
	if m.d != 0 {
		o['d'] = protobuf.json_u64(m.d)
	}
	if m.e != 0 {
		o['e'] = json2.Any(i64(m.e))
	}
	if m.f != 0 {
		o['f'] = protobuf.json_i64(m.f)
	}
	if m.g {
		o['g'] = json2.Any(m.g)
	}
	if m.h != '' {
		o['h'] = json2.Any(m.h)
	}
	if m.i.len > 0 {
		o['i'] = protobuf.json_b64(m.i)
	}
	if m.j != 0 {
		o['j'] = protobuf.json_f32(m.j)
	}
	if m.k != 0 {
		o['k'] = protobuf.json_f64(m.k)
	}
	if m.l != 0 {
		o['l'] = json2.Any(u64(m.l))
	}
	if m.m != 0 {
		o['m'] = protobuf.json_u64(m.m)
	}
	if m.n != 0 {
		o['n'] = json2.Any(i64(m.n))
	}
	if m.o != 0 {
		o['o'] = protobuf.json_i64(m.o)
	}
	if int(m.p) != 0 {
		o['p'] = color_to_json(m.p)
	}
	if m.rp.len > 0 {
		mut rp_a := []json2.Any{cap: m.rp.len}
		for v in m.rp {
			rp_a << json2.Any(i64(v))
		}
		o['rp'] = json2.Any(rp_a)
	}
	if m.rs.len > 0 {
		mut rs_a := []json2.Any{cap: m.rs.len}
		for v in m.rs {
			rs_a << json2.Any(v)
		}
		o['rs'] = json2.Any(rs_a)
	}
	if nested := m.nested {
		o['nested'] = nested.json_value()
	}
	if m.rn.len > 0 {
		mut rn_a := []json2.Any{cap: m.rn.len}
		for v in m.rn {
			rn_a << v.json_value()
		}
		o['rn'] = json2.Any(rn_a)
	}
	if m.mi.len > 0 {
		mut mi_o := map[string]json2.Any{}
		mut mi_ks := m.mi.keys()
		mi_ks.sort()
		for k in mi_ks {
			v := m.mi[k]
			mi_o[k.str()] = json2.Any(i64(v))
		}
		o['mi'] = json2.Any(mi_o)
	}
	if m.ms.len > 0 {
		mut ms_o := map[string]json2.Any{}
		mut ms_ks := m.ms.keys()
		ms_ks.sort()
		for k in ms_ks {
			v := m.ms[k]
			ms_o[k] = json2.Any(v)
		}
		o['ms'] = json2.Any(ms_o)
	}
	if m.mn.len > 0 {
		mut mn_o := map[string]json2.Any{}
		mut mn_ks := m.mn.keys()
		mn_ks.sort()
		for k in mn_ks {
			v := m.mn[k]
			mn_o[k] = v.json_value()
		}
		o['mn'] = json2.Any(mn_o)
	}
	if m.mc.len > 0 {
		mut mc_o := map[string]json2.Any{}
		mut mc_ks := m.mc.keys()
		mc_ks.sort()
		for k in mc_ks {
			v := m.mc[k]
			mc_o[k.str()] = color_to_json(v)
		}
		o['mc'] = json2.Any(mc_o)
	}
	if m.mb.len > 0 {
		mut mb_o := map[string]json2.Any{}
		mut mb_ks := m.mb.keys()
		mb_ks.sort()
		for k in mb_ks {
			v := m.mb[k]
			mb_o[k.str()] = json2.Any(v)
		}
		o['mb'] = json2.Any(mb_o)
	}
	if ov := m.choice {
		if ov is Scalars_Ci {
			o['ci'] = json2.Any(i64(ov.value))
		}
	}
	if ov := m.choice {
		if ov is Scalars_Cs {
			o['cs'] = json2.Any(ov.value)
		}
	}
	if ov := m.choice {
		if ov is Scalars_Cn {
			o['cn'] = ov.value.json_value()
		}
	}
	if ts := m.ts {
		o['ts'] = ts.json_value()
	}
	return json2.Any(o)
}

pub fn Scalars.from_json_value(a json2.Any) !Scalars {
	obj := protobuf.json_object(a)!
	mut m := Scalars{}
	for jk, jv in obj {
		if jv is json2.Null {
			continue
		}
		match jk {
			'a' {
				m.a = protobuf.json_int32v(jv)!
			}
			'b' {
				m.b = protobuf.json_intv(jv)!
			}
			'c' {
				m.c = protobuf.json_uint32v(jv)!
			}
			'd' {
				m.d = protobuf.json_uintv(jv)!
			}
			'e' {
				m.e = protobuf.json_int32v(jv)!
			}
			'f' {
				m.f = protobuf.json_intv(jv)!
			}
			'g' {
				m.g = protobuf.json_boolv(jv)!
			}
			'h' {
				m.h = protobuf.json_stringv(jv)!
			}
			'i' {
				m.i = protobuf.json_bytesv(jv)!
			}
			'j' {
				m.j = f32(protobuf.json_floatv(jv)!)
			}
			'k' {
				m.k = protobuf.json_floatv(jv)!
			}
			'l' {
				m.l = protobuf.json_uint32v(jv)!
			}
			'm' {
				m.m = protobuf.json_uintv(jv)!
			}
			'n' {
				m.n = protobuf.json_int32v(jv)!
			}
			'o' {
				m.o = protobuf.json_intv(jv)!
			}
			'p' {
				m.p = color_from_json(jv)!
			}
			'rp' {
				for it in protobuf.json_array(jv)! {
					m.rp << protobuf.json_int32v(it)!
				}
			}
			'rs' {
				for it in protobuf.json_array(jv)! {
					m.rs << protobuf.json_stringv(it)!
				}
			}
			'nested' {
				m.nested = Nested.from_json_value(jv)!
			}
			'rn' {
				for it in protobuf.json_array(jv)! {
					m.rn << Nested.from_json_value(it)!
				}
			}
			'mi' {
				for mk, mv in protobuf.json_object(jv)! {
					m.mi[int(protobuf.json_key_i64(mk)!)] = protobuf.json_int32v(mv)!
				}
			}
			'ms' {
				for mk, mv in protobuf.json_object(jv)! {
					m.ms[mk] = protobuf.json_stringv(mv)!
				}
			}
			'mn' {
				for mk, mv in protobuf.json_object(jv)! {
					m.mn[mk] = Nested.from_json_value(mv)!
				}
			}
			'mc' {
				for mk, mv in protobuf.json_object(jv)! {
					m.mc[u32(protobuf.json_key_u64(mk)!)] = color_from_json(mv)!
				}
			}
			'mb' {
				for mk, mv in protobuf.json_object(jv)! {
					m.mb[protobuf.json_key_i64(mk)!] = protobuf.json_boolv(mv)!
				}
			}
			'ci' {
				m.choice = Scalars_Ci{
					value: protobuf.json_int32v(jv)!
				}
			}
			'cs' {
				m.choice = Scalars_Cs{
					value: protobuf.json_stringv(jv)!
				}
			}
			'cn' {
				m.choice = Scalars_Cn{
					value: Nested.from_json_value(jv)!
				}
			}
			'ts' {
				m.ts = GoogleProtobuf_Timestamp.from_json_value(jv)!
			}
			else {}
		}
	}
	return m
}

pub struct GoogleProtobuf_Timestamp {
pub mut:
	seconds    i64
	nanos      int
	pb_unknown []u8 // unrecognized fields, re-emitted on encode
}

pub fn (m &GoogleProtobuf_Timestamp) encoded_size() int {
	mut n := 0
	if m.seconds != 0 {
		n += protobuf.tag_len(1) + protobuf.varint_len(u64(m.seconds))
	}
	if m.nanos != 0 {
		n += protobuf.tag_len(2) + protobuf.varint_len(u64(i64(m.nanos)))
	}
	return n + m.pb_unknown.len
}

pub fn (m &GoogleProtobuf_Timestamp) encode_to(mut e protobuf.Encoder) {
	if m.seconds != 0 {
		e.write_int64_field(1, m.seconds)
	}
	if m.nanos != 0 {
		e.write_int32_field(2, m.nanos)
	}
	e.write_raw(m.pb_unknown)
}

pub fn (m &GoogleProtobuf_Timestamp) encode() []u8 {
	mut e := protobuf.Encoder{
		buf: []u8{cap: m.encoded_size()}
	}
	m.encode_to(mut e)
	return e.buf
}

pub fn GoogleProtobuf_Timestamp.decode(buf []u8) !GoogleProtobuf_Timestamp {
	mut m := GoogleProtobuf_Timestamp{}
	mut d := protobuf.Decoder{
		buf: buf
	}
	for d.more() {
		tag_start := d.pos
		field, wt := d.read_tag()!
		match field {
			1 {
				m.seconds = d.read_int64()!
			}
			2 {
				m.nanos = d.read_int32()!
			}
			else {
				d.skip(wt)!
				m.pb_unknown << d.buf[tag_start..d.pos]
			}
		}
	}
	return m
}

// as_time converts to time.Time (UTC); out-of-spec nanos are clamped
pub fn (m &GoogleProtobuf_Timestamp) as_time() time.Time {
	mut n := m.nanos
	if n < 0 {
		n = 0
	} else if n > 999_999_999 {
		n = 999_999_999
	}
	return time.unix_nanosecond(m.seconds, n)
}

pub fn GoogleProtobuf_Timestamp.from_time(t time.Time) GoogleProtobuf_Timestamp {
	return GoogleProtobuf_Timestamp{
		seconds: t.unix()
		nanos:   t.nanosecond
	}
}

pub fn (m &GoogleProtobuf_Timestamp) json() string {
	return m.json_value().json_str()
}

pub fn GoogleProtobuf_Timestamp.from_json(s string) !GoogleProtobuf_Timestamp {
	return GoogleProtobuf_Timestamp.from_json_value(protobuf.json_parse(s)!)
}

// canonical JSON form: RFC 3339 in UTC
pub fn (m &GoogleProtobuf_Timestamp) json_value() json2.Any {
	t := time.unix(m.seconds)
	mut frac := ''
	if m.nanos != 0 {
		if m.nanos % 1_000_000 == 0 {
			frac = '.${(m.nanos / 1_000_000):03d}'
		} else if m.nanos % 1_000 == 0 {
			frac = '.${(m.nanos / 1_000):06d}'
		} else {
			frac = '.${m.nanos:09d}'
		}
	}
	return json2.Any('${t.year:04d}-${t.month:02d}-${t.day:02d}T${t.hour:02d}:${t.minute:02d}:${t.second:02d}${frac}Z')
}

pub fn GoogleProtobuf_Timestamp.from_json_value(a json2.Any) !GoogleProtobuf_Timestamp {
	s := protobuf.json_stringv(a)!
	t := time.parse_rfc3339(s) or { return error('protojson: bad timestamp `${s}`') }
	return GoogleProtobuf_Timestamp{
		seconds: t.unix()
		nanos:   t.nanosecond
	}
}
