// Code generated by protobuf.gen. DO NOT EDIT.
module main

import protobuf

pub enum Color {
	color_unspecified = 0
	red               = 1
	green             = 2
	blue              = 3
}

pub struct Nested {
pub mut:
	name string
	num  int
}

pub fn (m &Nested) encoded_size() int {
	mut n := 0
	if m.name != '' {
		n += protobuf.len_field_len(1, m.name.len)
	}
	if m.num != 0 {
		n += protobuf.tag_len(2) + protobuf.varint_len(u64(i64(m.num)))
	}
	return n
}

pub fn (m &Nested) encode_to(mut e protobuf.Encoder) {
	if m.name != '' {
		e.write_string_field(1, m.name)
	}
	if m.num != 0 {
		e.write_int32_field(2, m.num)
	}
}

pub fn (m &Nested) encode() []u8 {
	mut e := protobuf.Encoder{
		buf: []u8{cap: m.encoded_size()}
	}
	m.encode_to(mut e)
	return e.buf
}

pub fn Nested.decode(buf []u8) !Nested {
	mut m := Nested{}
	mut d := protobuf.Decoder{
		buf: buf
	}
	for d.more() {
		field, wt := d.read_tag()!
		match field {
			1 {
				m.name = d.read_string()!
			}
			2 {
				m.num = d.read_int32()!
			}
			else {
				d.skip(wt)!
			}
		}
	}
	return m
}

pub struct Scalars_Ci {
pub mut:
	value int
}

pub struct Scalars_Cs {
pub mut:
	value string
}

pub struct Scalars_Cn {
pub mut:
	value Nested
}

pub type Scalars_Choice = Scalars_Ci | Scalars_Cs | Scalars_Cn

pub struct Scalars {
pub mut:
	a      int
	b      i64
	c      u32
	d      u64
	e      int
	f      i64
	g      bool
	h      string
	i      []u8
	j      f32
	k      f64
	l      u32
	m      u64
	n      int
	o      i64
	p      Color
	rp     []int
	rs     []string
	nested ?Nested
	rn     []Nested
	mi     map[int]int
	ms     map[string]string
	mn     map[string]Nested
	mc     map[u32]Color
	mb     map[i64]bool
	choice ?Scalars_Choice
}

pub fn (m &Scalars) encoded_size() int {
	mut n := 0
	if m.a != 0 {
		n += protobuf.tag_len(1) + protobuf.varint_len(u64(i64(m.a)))
	}
	if m.b != 0 {
		n += protobuf.tag_len(2) + protobuf.varint_len(u64(m.b))
	}
	if m.c != 0 {
		n += protobuf.tag_len(3) + protobuf.varint_len(u64(m.c))
	}
	if m.d != 0 {
		n += protobuf.tag_len(4) + protobuf.varint_len(m.d)
	}
	if m.e != 0 {
		n += protobuf.tag_len(5) + protobuf.varint_len(protobuf.zigzag_encode(i64(m.e)))
	}
	if m.f != 0 {
		n += protobuf.tag_len(6) + protobuf.varint_len(protobuf.zigzag_encode(m.f))
	}
	if m.g {
		n += protobuf.tag_len(7) + 1
	}
	if m.h != '' {
		n += protobuf.len_field_len(8, m.h.len)
	}
	if m.i.len > 0 {
		n += protobuf.len_field_len(9, m.i.len)
	}
	if m.j != 0 {
		n += protobuf.tag_len(10) + 4
	}
	if m.k != 0 {
		n += protobuf.tag_len(11) + 8
	}
	if m.l != 0 {
		n += protobuf.tag_len(12) + 4
	}
	if m.m != 0 {
		n += protobuf.tag_len(13) + 8
	}
	if m.n != 0 {
		n += protobuf.tag_len(14) + 4
	}
	if m.o != 0 {
		n += protobuf.tag_len(15) + 8
	}
	if int(m.p) != 0 {
		n += protobuf.tag_len(16) + protobuf.varint_len(u64(i64(int(m.p))))
	}
	if m.rp.len > 0 {
		mut p := 0
		for v in m.rp {
			p += protobuf.varint_len(u64(i64(v)))
		}
		n += protobuf.len_field_len(17, p)
	}
	for v in m.rs {
		n += protobuf.len_field_len(18, v.len)
	}
	if nested := m.nested {
		n += protobuf.len_field_len(19, nested.encoded_size())
	}
	for v in m.rn {
		n += protobuf.len_field_len(20, v.encoded_size())
	}
	for k, v in m.mi {
		n += protobuf.len_field_len(21, protobuf.tag_len(1) + protobuf.varint_len(u64(i64(k))) +
			protobuf.tag_len(2) + protobuf.varint_len(u64(i64(v))))
	}
	for k, v in m.ms {
		n += protobuf.len_field_len(22, protobuf.len_field_len(1, k.len) +
			protobuf.len_field_len(2, v.len))
	}
	for k, v in m.mn {
		n += protobuf.len_field_len(23, protobuf.len_field_len(1, k.len) +
			protobuf.len_field_len(2, v.encoded_size()))
	}
	for k, v in m.mc {
		n += protobuf.len_field_len(24, protobuf.tag_len(1) + protobuf.varint_len(u64(k)) +
			protobuf.tag_len(2) + protobuf.varint_len(u64(i64(int(v)))))
	}
	for k, _ in m.mb {
		n += protobuf.len_field_len(25, protobuf.tag_len(1) +
			protobuf.varint_len(protobuf.zigzag_encode(k)) + protobuf.tag_len(2) + 1)
	}
	if ov := m.choice {
		if ov is Scalars_Ci {
			n += protobuf.tag_len(26) + protobuf.varint_len(u64(i64(ov.value)))
		}
	}
	if ov := m.choice {
		if ov is Scalars_Cs {
			n += protobuf.len_field_len(27, ov.value.len)
		}
	}
	if ov := m.choice {
		if ov is Scalars_Cn {
			n += protobuf.len_field_len(28, ov.value.encoded_size())
		}
	}
	return n
}

pub fn (m &Scalars) encode_to(mut e protobuf.Encoder) {
	if m.a != 0 {
		e.write_int32_field(1, m.a)
	}
	if m.b != 0 {
		e.write_int64_field(2, m.b)
	}
	if m.c != 0 {
		e.write_uint32_field(3, m.c)
	}
	if m.d != 0 {
		e.write_uint64_field(4, m.d)
	}
	if m.e != 0 {
		e.write_sint32_field(5, m.e)
	}
	if m.f != 0 {
		e.write_sint64_field(6, m.f)
	}
	if m.g {
		e.write_bool_field(7, m.g)
	}
	if m.h != '' {
		e.write_string_field(8, m.h)
	}
	if m.i.len > 0 {
		e.write_bytes_field(9, m.i)
	}
	if m.j != 0 {
		e.write_float_field(10, m.j)
	}
	if m.k != 0 {
		e.write_double_field(11, m.k)
	}
	if m.l != 0 {
		e.write_fixed32_field(12, m.l)
	}
	if m.m != 0 {
		e.write_fixed64_field(13, m.m)
	}
	if m.n != 0 {
		e.write_sfixed32_field(14, m.n)
	}
	if m.o != 0 {
		e.write_sfixed64_field(15, m.o)
	}
	if int(m.p) != 0 {
		e.write_int32_field(16, int(m.p))
	}
	if m.rp.len > 0 {
		mut p := 0
		for v in m.rp {
			p += protobuf.varint_len(u64(i64(v)))
		}
		e.write_tag(17, .len_delim)
		e.write_varint(u64(p))
		for v in m.rp {
			e.write_varint(u64(i64(v)))
		}
	}
	for v in m.rs {
		e.write_string_field(18, v)
	}
	if nested := m.nested {
		e.write_tag(19, .len_delim)
		e.write_varint(u64(nested.encoded_size()))
		nested.encode_to(mut e)
	}
	for v in m.rn {
		e.write_tag(20, .len_delim)
		e.write_varint(u64(v.encoded_size()))
		v.encode_to(mut e)
	}
	if m.mi.len > 0 {
		mut mi_keys := m.mi.keys()
		mi_keys.sort()
		for k in mi_keys {
			v := m.mi[k]
			e.write_tag(21, .len_delim)
			e.write_varint(u64(protobuf.tag_len(1) + protobuf.varint_len(u64(i64(k))) +
				protobuf.tag_len(2) + protobuf.varint_len(u64(i64(v)))))
			e.write_int32_field(1, k)
			e.write_int32_field(2, v)
		}
	}
	if m.ms.len > 0 {
		mut ms_keys := m.ms.keys()
		ms_keys.sort()
		for k in ms_keys {
			v := m.ms[k]
			e.write_tag(22, .len_delim)
			e.write_varint(u64(protobuf.len_field_len(1, k.len) + protobuf.len_field_len(2, v.len)))
			e.write_string_field(1, k)
			e.write_string_field(2, v)
		}
	}
	if m.mn.len > 0 {
		mut mn_keys := m.mn.keys()
		mn_keys.sort()
		for k in mn_keys {
			v := m.mn[k]
			e.write_tag(23, .len_delim)
			e.write_varint(u64(protobuf.len_field_len(1, k.len) +
				protobuf.len_field_len(2, v.encoded_size())))
			e.write_string_field(1, k)
			e.write_tag(2, .len_delim)
			e.write_varint(u64(v.encoded_size()))
			v.encode_to(mut e)
		}
	}
	if m.mc.len > 0 {
		mut mc_keys := m.mc.keys()
		mc_keys.sort()
		for k in mc_keys {
			v := m.mc[k]
			e.write_tag(24, .len_delim)
			e.write_varint(u64(protobuf.tag_len(1) + protobuf.varint_len(u64(k)) +
				protobuf.tag_len(2) + protobuf.varint_len(u64(i64(int(v))))))
			e.write_uint32_field(1, k)
			e.write_int32_field(2, int(v))
		}
	}
	if m.mb.len > 0 {
		mut mb_keys := m.mb.keys()
		mb_keys.sort()
		for k in mb_keys {
			v := m.mb[k]
			e.write_tag(25, .len_delim)
			e.write_varint(u64(protobuf.tag_len(1) +
				protobuf.varint_len(protobuf.zigzag_encode(k)) + protobuf.tag_len(2) + 1))
			e.write_sint64_field(1, k)
			e.write_bool_field(2, v)
		}
	}
	if ov := m.choice {
		if ov is Scalars_Ci {
			e.write_int32_field(26, ov.value)
		}
	}
	if ov := m.choice {
		if ov is Scalars_Cs {
			e.write_string_field(27, ov.value)
		}
	}
	if ov := m.choice {
		if ov is Scalars_Cn {
			e.write_tag(28, .len_delim)
			e.write_varint(u64(ov.value.encoded_size()))
			ov.value.encode_to(mut e)
		}
	}
}

pub fn (m &Scalars) encode() []u8 {
	mut e := protobuf.Encoder{
		buf: []u8{cap: m.encoded_size()}
	}
	m.encode_to(mut e)
	return e.buf
}

pub fn Scalars.decode(buf []u8) !Scalars {
	mut m := Scalars{}
	mut d := protobuf.Decoder{
		buf: buf
	}
	for d.more() {
		field, wt := d.read_tag()!
		match field {
			1 {
				m.a = d.read_int32()!
			}
			2 {
				m.b = d.read_int64()!
			}
			3 {
				m.c = d.read_uint32()!
			}
			4 {
				m.d = d.read_uint64()!
			}
			5 {
				m.e = d.read_sint32()!
			}
			6 {
				m.f = d.read_sint64()!
			}
			7 {
				m.g = d.read_bool()!
			}
			8 {
				m.h = d.read_string()!
			}
			9 {
				m.i = d.read_bytes()!
			}
			10 {
				m.j = d.read_float()!
			}
			11 {
				m.k = d.read_double()!
			}
			12 {
				m.l = d.read_fixed32()!
			}
			13 {
				m.m = d.read_fixed64()!
			}
			14 {
				m.n = d.read_sfixed32()!
			}
			15 {
				m.o = d.read_sfixed64()!
			}
			16 {
				m.p = unsafe { Color(d.read_int32()!) }
			}
			17 {
				if wt == .len_delim {
					mut sub := protobuf.Decoder{
						buf: d.read_view()!
					}
					for sub.more() {
						m.rp << sub.read_int32()!
					}
				} else {
					m.rp << d.read_int32()!
				}
			}
			18 {
				m.rs << d.read_string()!
			}
			19 {
				m.nested = Nested.decode(d.read_view()!)!
			}
			20 {
				m.rn << Nested.decode(d.read_view()!)!
			}
			21 {
				mut sub := protobuf.Decoder{
					buf: d.read_view()!
				}
				mut mk := 0
				mut mv := 0
				for sub.more() {
					mf, mw := sub.read_tag()!
					match mf {
						1 { mk = sub.read_int32()! }
						2 { mv = sub.read_int32()! }
						else { sub.skip(mw)! }
					}
				}
				m.mi[mk] = mv
			}
			22 {
				mut sub := protobuf.Decoder{
					buf: d.read_view()!
				}
				mut mk := ''
				mut mv := ''
				for sub.more() {
					mf, mw := sub.read_tag()!
					match mf {
						1 { mk = sub.read_string()! }
						2 { mv = sub.read_string()! }
						else { sub.skip(mw)! }
					}
				}
				m.ms[mk] = mv
			}
			23 {
				mut sub := protobuf.Decoder{
					buf: d.read_view()!
				}
				mut mk := ''
				mut mv := Nested{}
				for sub.more() {
					mf, mw := sub.read_tag()!
					match mf {
						1 { mk = sub.read_string()! }
						2 { mv = Nested.decode(sub.read_view()!)! }
						else { sub.skip(mw)! }
					}
				}
				m.mn[mk] = mv
			}
			24 {
				mut sub := protobuf.Decoder{
					buf: d.read_view()!
				}
				mut mk := u32(0)
				mut mv := unsafe { Color(0) }
				for sub.more() {
					mf, mw := sub.read_tag()!
					match mf {
						1 { mk = sub.read_uint32()! }
						2 { mv = unsafe { Color(sub.read_int32()!) } }
						else { sub.skip(mw)! }
					}
				}
				m.mc[mk] = mv
			}
			25 {
				mut sub := protobuf.Decoder{
					buf: d.read_view()!
				}
				mut mk := i64(0)
				mut mv := false
				for sub.more() {
					mf, mw := sub.read_tag()!
					match mf {
						1 { mk = sub.read_sint64()! }
						2 { mv = sub.read_bool()! }
						else { sub.skip(mw)! }
					}
				}
				m.mb[mk] = mv
			}
			26 {
				m.choice = Scalars_Ci{
					value: d.read_int32()!
				}
			}
			27 {
				m.choice = Scalars_Cs{
					value: d.read_string()!
				}
			}
			28 {
				m.choice = Scalars_Cn{
					value: Nested.decode(d.read_view()!)!
				}
			}
			else {
				d.skip(wt)!
			}
		}
	}
	return m
}
