// Code generated by protobuf.gen. DO NOT EDIT.
module main

import protobuf

pub enum Color {
	color_unspecified = 0
	red               = 1
	green             = 2
	blue              = 3
}

pub struct Nested {
pub mut:
	name string
	num  int
}

pub fn (m Nested) encode() []u8 {
	mut e := protobuf.Encoder{}
	if m.name != '' {
		e.write_string_field(1, m.name)
	}
	if m.num != 0 {
		e.write_int32_field(2, m.num)
	}
	return e.buf
}

pub fn Nested.decode(buf []u8) !Nested {
	mut m := Nested{}
	mut d := protobuf.Decoder{
		buf: buf
	}
	for d.more() {
		field, wt := d.read_tag()!
		match field {
			1 {
				m.name = d.read_string()!
			}
			2 {
				m.num = d.read_int32()!
			}
			else {
				d.skip(wt)!
			}
		}
	}
	return m
}

pub struct Scalars {
pub mut:
	a      int
	b      i64
	c      u32
	d      u64
	e      int
	f      i64
	g      bool
	h      string
	i      []u8
	j      f32
	k      f64
	l      u32
	m      u64
	n      int
	o      i64
	p      Color
	rp     []int
	rs     []string
	nested ?Nested
	rn     []Nested
}

pub fn (m Scalars) encode() []u8 {
	mut e := protobuf.Encoder{}
	if m.a != 0 {
		e.write_int32_field(1, m.a)
	}
	if m.b != 0 {
		e.write_int64_field(2, m.b)
	}
	if m.c != 0 {
		e.write_uint32_field(3, m.c)
	}
	if m.d != 0 {
		e.write_uint64_field(4, m.d)
	}
	if m.e != 0 {
		e.write_sint32_field(5, m.e)
	}
	if m.f != 0 {
		e.write_sint64_field(6, m.f)
	}
	if m.g {
		e.write_bool_field(7, m.g)
	}
	if m.h != '' {
		e.write_string_field(8, m.h)
	}
	if m.i.len > 0 {
		e.write_bytes_field(9, m.i)
	}
	if m.j != 0 {
		e.write_float_field(10, m.j)
	}
	if m.k != 0 {
		e.write_double_field(11, m.k)
	}
	if m.l != 0 {
		e.write_fixed32_field(12, m.l)
	}
	if m.m != 0 {
		e.write_fixed64_field(13, m.m)
	}
	if m.n != 0 {
		e.write_sfixed32_field(14, m.n)
	}
	if m.o != 0 {
		e.write_sfixed64_field(15, m.o)
	}
	if int(m.p) != 0 {
		e.write_int32_field(16, int(m.p))
	}
	if m.rp.len > 0 {
		mut sub := protobuf.Encoder{}
		for v in m.rp {
			sub.write_varint(u64(i64(v)))
		}
		e.write_bytes_field(17, sub.buf)
	}
	for v in m.rs {
		e.write_string_field(18, v)
	}
	if nested := m.nested {
		e.write_message_field(19, nested.encode())
	}
	for v in m.rn {
		e.write_message_field(20, v.encode())
	}
	return e.buf
}

pub fn Scalars.decode(buf []u8) !Scalars {
	mut m := Scalars{}
	mut d := protobuf.Decoder{
		buf: buf
	}
	for d.more() {
		field, wt := d.read_tag()!
		match field {
			1 {
				m.a = d.read_int32()!
			}
			2 {
				m.b = d.read_int64()!
			}
			3 {
				m.c = d.read_uint32()!
			}
			4 {
				m.d = d.read_uint64()!
			}
			5 {
				m.e = d.read_sint32()!
			}
			6 {
				m.f = d.read_sint64()!
			}
			7 {
				m.g = d.read_bool()!
			}
			8 {
				m.h = d.read_string()!
			}
			9 {
				m.i = d.read_bytes()!
			}
			10 {
				m.j = d.read_float()!
			}
			11 {
				m.k = d.read_double()!
			}
			12 {
				m.l = d.read_fixed32()!
			}
			13 {
				m.m = d.read_fixed64()!
			}
			14 {
				m.n = d.read_sfixed32()!
			}
			15 {
				m.o = d.read_sfixed64()!
			}
			16 {
				m.p = unsafe { Color(d.read_int32()!) }
			}
			17 {
				if wt == .len_delim {
					mut sub := protobuf.Decoder{
						buf: d.read_bytes()!
					}
					for sub.more() {
						m.rp << sub.read_int32()!
					}
				} else {
					m.rp << d.read_int32()!
				}
			}
			18 {
				m.rs << d.read_string()!
			}
			19 {
				m.nested = Nested.decode(d.read_bytes()!)!
			}
			20 {
				m.rn << Nested.decode(d.read_bytes()!)!
			}
			else {
				d.skip(wt)!
			}
		}
	}
	return m
}
